### ISSUE TITLE
Containing undesired command output in generated CI configs

### ISSUE THREAD

**Issue by akirak** [akirak/emacs-package-checker#13]
Running `melpa-check-generate-ci-config` on [lsp-dart](https://github.com/emacs-lsp/lsp-dart/) generated the following content:

```
these paths will be fetched (0.19 MiB download, 0.77 MiB unpacked):
  /nix/store/ar0yzyr3j6skidlvr0c4v6y8fz5i8m62-jq-1.6-dev
  /nix/store/f90g6z6r5pfg9zqzv9nya2k1mazh5khx-python3.7-PyYAML-5.2
  /nix/store/rkm9qp22h8w3i14yd47yzmbbkiiwfgzp-yq-2.8.1
  /nix/store/v4lrrp90adw8lqckglqzagxvm3b37a46-python3.7-xmltodict-0.12.0
copying path '/nix/store/ar0yzyr3j6skidlvr0c4v6y8fz5i8m62-jq-1.6-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/f90g6z6r5pfg9zqzv9nya2k1mazh5khx-python3.7-PyYAML-5.2' from 'https://cache.nixos.org'...
copying path '/nix/store/v4lrrp90adw8lqckglqzagxvm3b37a46-python3.7-xmltodict-0.12.0' from 'https://cache.nixos.org'...
copying path '/nix/store/rkm9qp22h8w3i14yd47yzmbbkiiwfgzp-yq-2.8.1' from 'https://cache.nixos.org'...
jobs:
  lint:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v8
      - uses: actions/checkout@v1
      - uses: akirak/emacs-package@v1
      - name: 'Lint (with Emacs version: latest)'
        run: melpa-check lint -e latest lsp-dart
  tests:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v8
      - uses: actions/checkout@v1
      - uses: akirak/emacs-package@v1
      - name: 'Byte-compile (with Emacs version: all)'
        run: melpa-check byte-compile -e all lsp-dart
      - name: 'Tests (with Emacs version: all)'
        run: melpa-check test -e all lsp-dart
name: lsp-dart CI
'on':
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.org'
```

Apparently, the initial lines are messages from nix, which shouldn't be included in the configuration file.
